apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o2qsv8ucf-nodejs 
  janus-idp.io/tekton: o2qsv8ucf-nodejs
  backstage.io/kubernetes-id: o2qsv8ucf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o2qsv8ucf-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml